version: "3"

services:
  app:
    build: ./app
    volumes:
      - ./app:/code:z
    tty: true
    ports:
      - 8000:8000
    container_name: django-container
  web:
    build: ./web
    volumes:
      - ./web:/code:z
    tty: true
    ports:
      - 8080:8080
    container_name: vue-container
    depends_on:
      - app
